name: Update Quote of the Day

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6AM UTC
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pick random quote
        run: |
          mapfile -t quotes < quotes.txt
          random_quote="${quotes[$RANDOM % ${#quotes[@]}]}"
          echo -e "<!-- QUOTE_START -->\n> ${random_quote}\n<!-- QUOTE_END -->" > quote.md

      - name: Update README
        run: |
          awk '/<!-- QUOTE_START -->/,/<!-- QUOTE_END -->/ {next} 1' README.md > temp.md
          cat quote.md >> temp.md
          mv temp.md README.md

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Daily quote update 🌟"
          git push
